AWSTemplateFormatVersion: "2010-09-09"
Description: This is create a test VPC in cloud formation
Resources:
  UdacityCFLabVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Udacity